hola: hello
sekai: world
students:
  Alice:
    message: good
    nekos:
      cat1: jbcat
      cat2: ooo
  Joe:
    favorNumbers:
      - 114
      - 514
      - 000
    message: thaumy12384
    phone: 1951327599
AwesomeSite:
  url: http://cdn.thaumy.cn/
Goods:
  -
    fruits:
      -
        co: apple
        keyborad: qwert
      - banana
      - cherry
  - id1: 1
  - hybrid
List:
  - 12384
