934770716910:
  first_name: Thaumy
  last_name: Cheng
  sex: male
  phone: 1234567890
  hobby: 
    - coding
    - read book
    - fishing
385271188675:
  first_name: Alice
  last_name: Miyabi
  sex: female
  phone: 1527561890
  hobby: 
    - small talk
    - sleeping
105507332749:
  first_name: Tim
  last_name: Cook
  sex: male
  phone: 1136569821
  hobby: 
    - #This hobby can be broken down
      sell_things:
        - iphone
        - mac
        - etc
    - 
      - a
      - b
    - clear inventory